-- Seed data: Kharkiv, Ukraine area
-- Run AFTER the migrations

INSERT INTO reports (category, severity, title, description, latitude, longitude, location_name, status, confirmations, expires_at) VALUES
('shelling', 'critical', 'Active shelling near Saltivka district', 'Continuous artillery fire heard from the northeast. Multiple explosions in the last 30 minutes.', 50.0312, 36.2801, 'Saltivka, Kharkiv', 'active', 12, NOW() + INTERVAL '4 hours'),
('checkpoint', 'medium', 'Military checkpoint at Pyatykhatky', 'Ukrainian military checkpoint active. ID checks required. Wait time approximately 20 minutes.', 50.0198, 36.2067, 'Pyatykhatky, Kharkiv', 'active', 22, NOW() + INTERVAL '24 hours'),
('blocked_road', 'high', 'Road blocked by debris on Sumska St', 'Sumska Street blocked between Metro Universytet and Derzhprom due to building collapse debris.', 49.9935, 36.2304, 'Sumska St, Central Kharkiv', 'active', 18, NOW() + INTERVAL '12 hours'),
('safe_passage', 'positive', 'Safe corridor via Poltavsky Shlyakh', 'Route via Poltavsky Shlyakh confirmed safe for civilian passage. No military activity in last 2 hours.', 49.9812, 36.2678, 'Poltavsky Shlyakh, Kharkiv', 'active', 31, NOW() + INTERVAL '6 hours'),
('shelter_available', 'positive', 'Metro station shelter open 24/7', 'Universytet Metro station shelter fully operational. Space available for ~200 more people.', 49.9934, 36.2298, 'Metro Universytet, Kharkiv', 'active', 45, NOW() + INTERVAL '24 hours'),
('aid_distribution', 'positive', 'Food distribution at School #45', 'Hot meals and water distribution happening at School #45 until 18:00.', 49.9956, 36.2512, 'School #45, Kharkiv', 'active', 28, NOW() + INTERVAL '12 hours'),
('safe_passage', 'positive', 'Evacuation bus from South Station', 'Evacuation buses departing from Pivdenny Vokzal every 2 hours to Poltava. Next bus at 14:00.', 49.9678, 36.2189, 'South Station, Kharkiv', 'active', 52, NOW() + INTERVAL '6 hours'),
('military_presence', 'high', 'Drone activity over Northern Saltivka', 'Multiple drone sightings reported over Northern Saltivka. Stay indoors and away from windows.', 50.0456, 36.2789, 'Northern Saltivka, Kharkiv', 'active', 6, NOW() + INTERVAL '4 hours');

INSERT INTO resources (type, name, description, latitude, longitude, address, status, phone, operating_hours, capacity, services, source, verified) VALUES
('hospital', 'Kharkiv Regional Clinical Hospital', 'Main regional hospital with trauma center and emergency department.', 49.9923, 36.2156, '13 Nezalezhnosti Ave, Kharkiv', 'open', '+380577113456', '24/7', 800, '["emergency","surgery","trauma","icu","pediatrics"]'::jsonb, 'manual', true),
('hospital', 'City Emergency Hospital #4', 'Emergency hospital specializing in trauma and blast injuries.', 50.0034, 36.2389, '7 Saltivske Shosse, Kharkiv', 'limited_service', '+380577234567', '24/7', 350, '["emergency","surgery","trauma"]'::jsonb, 'manual', true),
('shelter', 'Metro Universytet Station Shelter', '24/7 underground shelter in metro station. Has electricity, water, and heating.', 49.9934, 36.2298, 'Metro Universytet, Kharkiv', 'open', null, '24/7', 500, '["beds","water","electricity","heating","first_aid","wifi"]'::jsonb, 'manual', true),
('shelter', 'Derzhprom Underground Parking Shelter', 'Converted underground parking used as civilian shelter.', 49.9998, 36.2312, 'Derzhprom, Freedom Square, Kharkiv', 'open', null, '24/7', 1000, '["water","electricity","heating"]'::jsonb, 'manual', true),
('water_point', 'Water Distribution Point (Barabashova)', 'Clean water distribution managed by Red Cross. Bring your own containers.', 49.9956, 36.2612, 'Barabashova Market Entrance, Kharkiv', 'open', null, '07:00-19:00', null, '["drinking_water","wash_water"]'::jsonb, 'manual', true),
('food_distribution', 'World Central Kitchen (South Station)', 'WCK hot meal distribution point at South Railway Station.', 49.9678, 36.2189, 'Pivdenny Vokzal, Kharkiv', 'open', null, '10:00-16:00', null, '["hot_meals","water","baby_food"]'::jsonb, 'manual', true),
('charging_station', 'Invincibility Point (City Hall)', 'Free charging, wifi, warmth, and tea.', 49.9934, 36.2301, 'City Hall, Konstytutsii Square, Kharkiv', 'open', null, '08:00-22:00', 100, '["phone_charging","wifi","heating","tea","info_desk"]'::jsonb, 'manual', true),
('transit_hub', 'Kharkiv South Railway Station', 'Main railway station. Evacuation trains to Poltava and Dnipro running daily.', 49.9678, 36.2189, 'Pryvokzalna Square, Kharkiv', 'open', '+380577890123', '24/7', null, '["evacuation_trains","information","shelter","wc"]'::jsonb, 'manual', true),
('ngo_office', 'UNHCR Kharkiv Office', 'UN refugee agency. Registration, legal aid, and emergency supplies.', 49.9912, 36.2345, '10 Sumska St, Kharkiv', 'open', '+380577901234', '09:00-17:00 Mon-Fri', null, '["registration","legal_aid","emergency_supplies","psychosocial_support"]'::jsonb, 'manual', true);
